### ISSUE TITLE
SmarGrid

### ISSUE THREAD

**Issue by Vitalb25** [andreyalexeich/gulp-pug-starter#104]
Как то не правильно создается scss файл для smardGrid'a
![image](https://user-images.githubusercontent.com/37478975/79153077-f3340480-7dd5-11ea-9c8b-f28aeb1067d6.png)

Когда генерируется файл то переменная объявляется ниже где она используется из-за этого вылазят ошибки. Либо я что то недопонимаю, либо ошибка

**Comment by andreyalexeich** [comment]
@Vitalb25 напиши автору плагина, не знаю, почему так

**Comment by Vitalb25** [comment]
есть отдельная сборка - там такой проблемы нету. думаю что то именно тут

**Comment by andreyalexeich** [comment]
ты же понимаешь, что я в коде плагина вряд ли что-то менял)

**Comment by Vitalb25** [comment]
может тогда стоит его выпилить раз он не функциональный на выходе получается)
