### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by liteCarma** [andreyalexeich/gulp-pug-starter#105]
Здравствуйте! Не могу понять в чем концептуальное отличие между компонентами и блоками. Спасибо!

**Comment by dsuhov** [comment]
В моем понимании, это часто используемые элементы, которые создаются как миксины. Я обычно собираю там всякие кнопки, стрелки, поля ввода и т.п.

**Comment by andreyalexeich** [comment]
> В моем понимании, это часто используемые элементы, которые создаются как миксины. Я обычно собираю там всякие кнопки, стрелки, поля ввода и т.п.

Именно так
