### ISSUE TITLE
Ошибка при подключении нового компонента

### ISSUE THREAD

**Issue by hexy** [andreyalexeich/gulp-pug-starter#107]
При создании нового компонента генерируется такой типовой код

`
modules.define("decor-btn", ["i-bem-dom"], function(provide, bemDom) {
    provide(bemDom.declBlock(this.name, {
        onSetMod: {
            js: {
                inited: function() {
                    //some js
                }
            }
        }
    }));
});
`

в итоге линтер ругается на этот компонент "error  'modules' is not defined  no-undef"  и на странице возникают аналогичные ошибки "decor-btn.js:2 Uncaught TypeError: Cannot read property 'define' of undefined"

как объявить modules и в чем может быть проблема?

**Comment by andreyalexeich** [comment]
Привет, этот код нужно удалять
