### ISSUE TITLE
Source maps для css, работают неправильно

### ISSUE THREAD

**Issue by ndeviant** [andreyalexeich/gulp-pug-starter#45]
Воспроизводится очень просто: запустить новый проект, посмотреть стили картинки 'img-responsive', source maps ссылаются на файл "_main.scss", где нету описания такого класса.
Дело в том, что gulp-sourcemaps не поддерживает плагин gulp-group-css-media-queries. Решается довольно просто: https://toster.ru/q/405218#comment_1540527
____________________
P.S., благодарю за крутую сборку. Сделал себе форк с использованием nunjucks вместо pug'a.

**Comment by andreyalexeich** [comment]
@ndeviant У меня не получается настроить этот плагин, вылетает с ошибками:

```TypeError: a.localeCompare is not a function```

```js
.pipe(postcss([
		mqpacker({
			sort: sortCSSmq
		})
	]))
```

**Comment by ndeviant** [comment]
Сделал пулл реквест, ещё сделал небольшой фикс для pngquant
https://github.com/andreyalexeich/gulp-pug-starter/pull/47
