### ISSUE TITLE
sass autoprefixer

### ISSUE THREAD

**Issue by NickolasDzR** [andreyalexeich/gulp-pug-starter#73]
Не подскажите, как подключить autoprefixer?

**Comment by andreyalexeich** [comment]
@NickolasDzR он есть в сборке, включен для продакшена (то есть тогда, когда нужно выкладывать проект на хостинг. Во время разработки автопрефиксер включать нет смысла)

**Comment by NickolasDzR** [comment]
Я понял. Спасибо за сборку, очень крутая
