### ISSUE TITLE
WebP поддержка в HTML

### ISSUE THREAD

**Issue by Twixxik** [andreyalexeich/gulp-pug-starter#89]
Можно добавить поддержку WebP.
Авто замена <img> на <picture>...
Полная поддержка браузерами. В браузерах где нет поддержки webp будет использоваться обычный формат.

Плагины для views: 
gulp-webp-html - выполняет замену. (есть недочеты в плагине, для их исправления можно подключить доп плагины)
gulp-html-prettify - вызывать до gulp-webp-html (для обработки инлайновых элементов)
gulp-htmlmin - для исправления структуры документа после gulp-webp-html (production)

Проверено - работает.

**Comment by rushelex** [comment]
Привет. Сделай PR, будет понятнее + больше шансов, что будет добавлено в сборку.

**Comment by rushelex** [comment]
> Можно добавить поддержку WebP.

Привет. Сделай PR, будет понятнее + больше шансов, что будет добавлено в сборку.
