### ISSUE TITLE
vendor.js - not found

### ISSUE THREAD

**Issue by vladbuich** [andreyalexeich/gulp-pug-starter#99]
Добрый день, спасибо за проект. 
Сейчас при первой установке и запуске (yarn run dev) ловлю ошибку в консоли браузера vendor.js - not found (404). В чем проблема может быть?

**Comment by andreyalexeich** [comment]
@vladbuich привет, значит ты ещё не использовал библиотеки, всё ок

**Comment by vladbuich** [comment]
@andreyalexeich понял, спасибо
